services:
  stock_db:
    image: postgres:18
    container_name: stock_db
    environment:
      POSTGRES_DB: stock_api
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - stock_api_pgdata:/var/lib/postgresql

  app:
    build: .
    container_name: stock_api
    depends_on:
      - stock_db
    ports:
      - "8081:8081"
    env_file:
      - .env

volumes:
  stock_api_pgdata:
